### ISSUE TITLE
Add convenience function `apply_bestNormalize` for direct access to transformed data

### ISSUE THREAD

**Issue by rempsyc** [petersonR/bestNormalize#15]
First, thank you very much for this wonderful package and the accompanying paper, which we can cite. Pardon me if there already is a function accomplishing the goal below and that I have overlooked it.

In order to have clean and elegant code for sharing with fellow scientists on, e.g., Open Science Framework, I am defining a convenience function that simply extracts the transformed data directly. Here is the current workflow:
```r
# Load package
library(bestNormalize)
library(dplyr)

# Define transform function
apply_bestNormalize <- function(var, print.transform = TRUE, standardize = TRUE) {
x <- bestNormalize(var, standardize = standardize)
  if (print.transform == TRUE) {
    print(cur_column())
    print(x$chosen_transform)
    cat("\n")
  }
  predict(x)
}

# Select all necessary variables
col.list <- autotrader %>% 
  select(price:mileage) %>% 
  names()

# Make histograms to check normality
lapply(autotrader[col.list], hist)

# Transform variables
autotrader2 <- autotrader %>% 
  mutate(across(all_of(col.list), 
                apply_bestNormalize,
                .names = "{.col}.BN"))

# Make histograms again to see if normality is now respected
col.list.BN <- paste0(col.list, ".BN")
lapply(autotrader2[col.list.BN], hist)
```
Instead of adding in my own script however, I was wondering if you could add such a function so that we may use it directly and have a shorter script. I just made the function name `apply_bestNormalize` up but it could be anything, like `predict_bestNormalize` or anything else. Alternatively, it could just be an additional argument of `bestNormalize`, something like, `output = "dataframe"` or `output = "predict"` with default `output = "full"`.

I am aware that it is often not recommended to use a black-box approach whereas one applies a bunch of functions without looking at available information at every step (like the important information that `bestNormalize` provides). However, this would be for the sole purpose of sharing concise code. Additional information on the function inner workings would easily be available as I would explicitly load your library and also cite your 2020 and 2021 papers for the interested reader.

Another concern of this direct approach might be insufficient attention given to the number of folds and repeats, but that's assuming the person using the function is doing so in full awareness of the proper requirements. Let me know your thoughts.

**Comment by petersonR** [comment]
Thank you for the suggestion and the example; However, calling `predict_bestNormalize(x)` and calling `predict(bestNormalize(x))` are equally concise in my opinion, but the former has a bigger potential to be abused.  Note that the code below will not need a new function (object), but is the same amount of lines of code as it would be under the proposed solution. 

```
autotrader2 <- autotrader %>% 
  mutate(across(all_of(col.list), 
                function(x) predict(bestNormalize(x)),
                .names = "{.col}.BN"))
```

**Comment by rempsyc** [comment]
Thank you for considering my suggestion and for the proposed solution. I agree that the former has perhaps a bigger potential to be abused. What I liked about it though is that it prints the chosen method to the console as it executes, whereas the suggested method doesn't. It gives a way to easily track what is going on without having to go through the full output manually every time. I am not really comfortable transforming the data without printing the chosen transformation, but at the same time I do not really want to have to perform it in separate steps. Colleagues of mine with whom I've consulted agree that we should not transform without declaring what transformations were used. I suppose I will go back to using the user-defined function above for now.

That said, one could also use a hybrid approach:

```r
autotrader2 <- autotrader %>% 
    mutate(across(all_of(col.list), 
                  function(x) {y <- bestNormalize(x)
                      print(cur_column())
                      print(y$chosen_transform)
                      cat("\n")
                      predict(y)},
                  .names = "{.col}.BN"))
```
