### ISSUE TITLE
New transformation: reverse log (and or other reverse transformations)

### ISSUE THREAD

**Issue by rempsyc** [petersonR/bestNormalize#18]
I am aware that one can [feed custom functions to `bestNormalize`](https://petersonr.github.io/bestNormalize/articles/customization.html). However, I am wondering if it would be worth adding this particular transformation to the package.

A colleague has observed that he obtains a better transformation (i.e., more normally distributed variable) when reversing scores of his variable, and then using a log (and eventually reversing scores once again), than the default selected choice with `bestNormalize`.

A couple of questions then:
- Is this expected/does it make any sense?
- Would it be worthwhile to implement it in the package?
- Would you have the time to implement it/would you rather me submitting a PR?
- If we are to include the procedure to reverse scores before using the log transform, should a similar procedure be applied to all other methods (if it changes anything; except maybe Box-Cox and Yeo-Jonhson)? That would almost double the number of transformations available.

**Comment by petersonR** [comment]
Interesting idea. By "reverse" I'm guessing your colleage is taking max(x) - x before applying the log transformation? I've had similar luck with heavily left-skewed data, like test scores. 

However, all of the transformations so far by default in `bestNormalize` preserve the ordering of observations, which may be important depending on the use-case. Reversing the ordering would of course no longer preserve it. So I'm not sure I'm fully on board with adding this as a default transformation; the meaning of "high" and "low" values could potentially get reversed and cause confusion. 

That said though, I'm wondering if it might make sense to add an option to `bestNormalize` like `attempt_reversal = FALSE` which if set to TRUE would run through all transformations on `max(x) - x` (the reverse ordered vector), thereby doubling the number of transformations done. I'd be open to this, but probably won't have time to go in and implement any time soon.

**Comment by rempsyc** [comment]
Cool, thank you!

> By "reverse" I'm guessing your colleage is taking max(x) - x before applying the log transformation? I've had similar luck with heavily left-skewed data, like test scores.

Yes, exactly, like `rempsyc::nice_reverse`:

```r
rempsyc::nice_reverse(5, max = 5)
[1] 1
```

Like you, our use case is for test scores. Furthermore, as mentioned earlier, we can simply reverse scores after the transformation is complete. So step 1 = reverse, step 2 = transform, step 3 = reverse again. Thus, there are two reverse scorings happening, and in this way, `bestNormalize` should preserve the ordering of observations.

> I'd be open to this, but probably won't have time to go in and implement any time soon.

If you agree, I could make an attempt at an initial PR that you could then review at your leisure.

**Comment by petersonR** [comment]
Ah I see. It's a good idea, but to use with `bestNormalize` one has to specify both the transformation and its inverse.  The double reverse might make things tricky from an inverse function perspective. What's the inverse of the function below? 

```r
f <- function(x) max(log(max(x) - x + 1)) - log(max(x) - x + 1)
plot(f, from = -1, to = 10)
```

**Comment by petersonR** [comment]
I suppose if the minimum and maximum are both known/trained, then this inverse is given by 

```r 
f_inv <- function(x.t, min_x = -1, max_x = 10) 
  (min_x - max_x -1)*exp(-x.t) + max_x + 1
```

in the case of the double-reverse logarithm, might be harder to work this out for the other transformations. If you'd like to attempt to write this into a new transformation (called something like `double_reverse_log`) I'd be happy to incorporate.

**Comment by rempsyc** [comment]
Correct, the `nice_reverse` function is simply defined as:

```r
nice_reverse <- function(x, max, min = 1) {
    max - as.numeric(x) + min
}
```
Instead of incorporating the reverse within the `double_reverse_log` function, I was simply thinking of a wrapper around other transformations, e.g. for a simplified example,

```r
double_reverse_log <- function(x) {
  x <- nice_reverse(x)
  x <- log(x)
  x <- nice_reverse(x)
}
```
I will play with it a bit and hopefully, I'll get to identify the potential challenges with the inverse functions and iron out any bugs. Even if we only add the double reverse for the log transformation (for now), I think it's already added value.

**Comment by petersonR** [comment]
Sounds good. I would use as a model the `bestNormalize::log_x()` function [here](https://github.com/petersonR/bestNormalize/blob/master/R/log_x.R). Note the reverse transformation must be functionally specified in the`predict.log_x` function when `inverse = TRUE`; this is where I anticipate the difficulty may lie. Let me know if you have any questions. Thanks for contributing.

**Comment by petersonR** [comment]
I think this is a go now! Thanks for the help, and let me know if you run into issues.
