### ISSUE TITLE
Bug in boxcox

### ISSUE THREAD

**Issue by suntzuisafterU** [petersonR/bestNormalize#22]
First I would like to say, fantastic idea for a library! Really enjoy it!

Unfortunately I have observed a bug in the boxcox transformation.  I can not share data but have observed a discontinuity at the lower end of the transformation that was not present when I reimplemented myself in python.  Specifically the data jumped from what should have been about -2 all the way to -20.

**Comment by petersonR** [comment]
Thank you- unfortunately if I can't reproduce the issue it's very difficult to debug. Can you provide a "shuffled" version of the vector you are passing through to boxcox? And the code you are using?

**Comment by petersonR** [comment]
As this is unresponsive and not reproducible I will have to close for now.
