### ISSUE TITLE
Improvement: add `allow_lambertw_hh = TRUE/FALSE` option; improved results for skewed, heavy tailed (unimodal) data

### ISSUE THREAD

**Issue by gmgeorg** [petersonR/bestNormalize#24]
Feature request to add `allow_lambertw_hh = TRUE/FALSE` as an option in bestNormalize.  this will be a preferred option for the 3 categories of Lambert W x F distributions when the observed data is skewed and heavy-tailed.

**Comment by petersonR** [comment]
This is now possible. For conciseness I have it now set so setting `allow_lambert_h = TRUE` turns on both the lambert methods of type "h" and "hh" as candidate transformations. @gmgeorg let me know if you run into issues, otherwise closing for now!
