### ISSUE TITLE
How can I calculate confidence interval of predicted value? 

### ISSUE THREAD

**Issue by cardiomoon** [petersonR/bestNormalize#3]
First of all, thank you very much for your package.

I have one question. 
How can I calculate confidence interval of predicted value? 
I tried to use predict() function with se.fit=TRUE, but it did not work.
I wish I could get the se.fit of predicted value(of course with inverse=TRUE option)

Best,
Keon-Woong Moon

**Comment by petersonR** [comment]
Unfortunately these transformations do not allow easy estimation of SE. I'm not sure it even makes sense to calculate SE for a transformation. If x.t = g(x), you'd want g-1(x.t) = x without error, such that the transformation is 1-1. Therefore, the `predict()` method (`predict.bestNormalize`) does not have an se.fit option; there's no fit from which to calculate SE.

Are you asking about how to calculate SE in the context of a regression using transformed variables, where `fit <- lm(y ~ x.t)` or `fit <- lm(y.t ~ x)`? If so, you should be able to utilize `predict.lm`, or `predict.glm` functions on the `fit` object with se.fit = TRUE, potentially passing through a `newdata` argument as well of your transformed variable.

**Comment by cardiomoon** [comment]
Thank you for your prompt reply. 
I will try with predict.lm function.
Best,
Keon-Wmmong Moon
