### ISSUE TITLE
pkgdown site

### ISSUE THREAD

**Issue by topepo** [petersonR/bestNormalize#7]
If you were to implement a `pkgdown` site, we could include your recipe step in the function reference on [`tidymodels.org`](https://www.tidymodels.org/find/recipes/). 

There are some easy functions to set this up to run automatically, such as `usethis::use_github_action("pkgdown")`. I can help if you need to get it configured.

**Comment by petersonR** [comment]
I'd be happy to implement a pkgdown site. I used the `usethis` function you mentioned, but I'm a little unsure how to complete the set up from here. Is it as simple as editing a few lines in the .github/workflows/pkgdown.yaml file? If not, can I take you up on your offer of help to get it configured? Or, if you could point me to a tutorial in doing so, that works too. Thanks!

**Comment by topepo** [comment]
Now I suggest using `usethis::use_tidy_github_actions()`; it sets up a lot of stuff in general. We've started using the `pak` package for installs; it really cuts down on the random errors using `install.packages()`. That's new so you might want to re-create them. 

After that, you can go to the settings and look for _GitHub Pages_. From there, use 

![image](https://user-images.githubusercontent.com/5731043/110400894-78f01c80-8046-11eb-973d-f4ca8810f1f8.png)

and, after about 15 min, use this option: 

![image](https://user-images.githubusercontent.com/5731043/110400918-8c9b8300-8046-11eb-8455-f968a435f7e3.png)

The link to the site would then be `https://petersonR.github.io/bestNormalize`. You should put that in the URL field of the DESCRIPTION file _after_ the current url. 

One detail: when you have a .9000-ish version number, it puts the files in a `dev` path. For example, the non-9000 link would look like [`https://pkgdown.r-lib.org/`](https://pkgdown.r-lib.org) while the dev version is found at [`https://pkgdown.r-lib.org/dev`](https://pkgdown.r-lib.org/dev). 

You might want to run the action with `Version: 1.7.0` and once again with `Version: 1.7.0.9999` to get both sites.

**Comment by petersonR** [comment]
Thanks for the suggestions! I've used the `usethis` package and set up a lot of stuff, as you said. I tried to implement the `pak` package, but got an odd error when trying to do so. I will update the version to 1.8.0 soon, and release the non-dev version of the packagedown website at that time and close this issue. Hopefully with the new website, this can be added to [tidymodels.org](url)? Let me know if there's more I can do to help set that up.

**Comment by petersonR** [comment]
Version 1.8.0 now published to CRAN and `pkgdown` documentation is up: https://petersonr.github.io/bestNormalize/. Please let me know if there's anything else I can do to help get this onto the tidymodels.org recipes list - for now though I'm going to close this.
